-- Remove anonymous write access to `scores` added in supabase_migration_v2.sql:
-- "Allow anonymous update" let any holder of the public anon key overwrite any
-- row (USING (true) WITH CHECK (true), no ownership check). No code in this
-- repo uses this table today (the Kiosk/local leaderboard is localStorage-only
-- - see CLAUDE.md), so nothing here depends on anonymous UPDATE continuing to
-- work. The original anonymous INSERT/SELECT policies from supabase_migration.sql
-- are left in place: they're appropriate for a public leaderboard (submit a new
-- score, read everyone's scores) and don't let a caller clobber someone else's
-- existing row the way the UPDATE policy did.
--
-- Not applied automatically: like supabase_migration.sql and
-- supabase_migration_v2.sql before it, this file has to be run by hand in the
-- Supabase project's SQL editor. This repo's only CI step (.github/workflows/
-- ci.yml) runs `npm ci` + `npm run build`; there is no deploy workflow and no
-- step anywhere that applies Supabase migrations.
DROP POLICY "Allow anonymous update" ON scores;
