-- Seeds the shipped content pack (src/assets/Vocab/LocalHistorySentences.json
-- at the time this migration was written) into the shared store.
INSERT INTO content_sources (id, topic, text) VALUES ('seed-wj1a41xb', 'Bridgerland Technical College', 'Bridgerland Technical College was founded on September 17, 1971.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-uvr7lafs', 'Bridgerland Technical College', 'The college first opened its doors in October of 1971.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-k7dak15u', 'Bridgerland Technical College', 'Bridgerland began as a vocational center serving Cache, Box Elder, and Rich counties.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-xnnyo7im', 'Bridgerland Technical College', 'In 1984, Bridgerland moved into a building that once made Wurlitzer pianos.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-rxct34vy', 'Bridgerland Technical College', 'The Logan campus of Bridgerland still sits on the site of that old piano factory.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-knc2p819', 'Bridgerland Technical College', 'Bridgerland Technical College has carried four different names since it began.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-ft0x6t3t', 'Bridgerland Technical College', 'Bridgerland trains welders, nurses, and machinists right here in Cache Valley.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-ojp0dq3n', 'Bridgerland Technical College', 'Bridgerland prepares students for skilled careers without requiring a four year degree.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-r8or4fy2', 'Bridgerland Technical College', 'The Logan campus started out as a Wurlitzer factory that made pianos and electronic organs.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-1i94s7f2', 'Bridgerland Technical College', 'Bridgerland turned the old Wurlitzer factory''s assembly lines into classrooms.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-978vi0s8', 'Bridgerland Technical College', 'Because of its factory roots, Bridgerland''s Logan campus is one large building under a single roof.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-ze8944x6', 'Bridgerland Technical College', 'Before settling in Logan, Bridgerland spent thirteen years moving between spaces like the old Tueller Dance Studio and rooms at Utah State University.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-mo171gs9', 'Bridgerland Technical College', 'The Brigham City campus later expanded into the former Bourns building.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-ro6egqq2', 'Bridgerland Technical College', 'Bridgerland''s Health Sciences building was Utah''s top funded project in 2020, lost that funding to COVID, and was refunded in 2021.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-aecdf8go', 'Bridgerland Technical College', 'Dr. Richard L. Maughan led Bridgerland for 40 years, one of the longest tenures of any Utah college president.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-zn7akxjd', 'Bridgerland Technical College', 'Today, Bridgerland still serves Cache, Box Elder, and Rich counties from campuses in Logan and Brigham City.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-8jj7mxp6', 'Bridgerland Technical College', 'Bridgerland runs the only student operated retail meat shop of its kind in the western United States.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-yf1k6pv8', 'Bridgerland Technical College', 'Bridgerland''s Veterinary Assisting students train hands-on at real veterinary clinics and animal facilities.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-wlxn0dut', 'Bridgerland Technical College', 'Bridgerland''s robotics students train on the same brand of industrial robots used across auto and aerospace manufacturing.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-rdg4f5sq', 'Cache Valley', 'Cache Valley stretches across the border between Utah and Idaho.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-94olxbia', 'Cache Valley', 'Shoshone people hunted and fished in Cache Valley long before settlers arrived.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-a87bddpq', 'Cache Valley', 'The Northwestern Band of Shoshone called themselves the Pangwiduka, or fish eaters.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-dca53xb3', 'Cache Valley', 'Settlers first tried to winter cattle in Cache Valley during 1855.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-rckb4pvx', 'Cache Valley', 'Peter Maughan founded a lasting settlement in Cache Valley in 1856.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-i3kgmys9', 'Cache Valley', 'That settlement grew into Wellsville, one of the valley''s oldest towns.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-jdj0r7al', 'Cache Valley', 'Cache County was created by the Utah territorial legislature in 1856.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-dudvzkuc', 'Cache Valley', 'Fur trappers are said to have cached, or stored, pelts here, giving the valley its name.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-fgbupgkv', 'Cache Valley', 'Logan was first settled in April of 1859 and named after the nearby Logan River.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-2w078yul', 'Cache Valley', 'Logan was incorporated as a town on January 17, 1866.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-vjswjzbs', 'Cache Valley', 'Construction on the Logan Tabernacle began in 1865 and finished in 1878.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-5f92ki8m', 'Cache Valley', 'The territorial legislature established what is now Utah State University in March of 1888.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-xh4dlbn3', 'Box Elder County', 'Box Elder County was separated from Weber County by the legislature in 1856.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-5lb2fz6g', 'Box Elder County', 'Brigham City has served as the seat of Box Elder County since it was founded.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-qkhet6ti', 'Box Elder County', 'Pioneer William Davis first explored the area near Brigham City in 1850.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-f3y4owzm', 'Box Elder County', 'The town was first called Box Elder before it was renamed Brigham City in 1877.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-we8ukn96', 'Box Elder County', 'On May 10, 1869, workers drove the Golden Spike at Promontory Summit.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-seiyicy3', 'Box Elder County', 'That ceremony joined the first transcontinental railroad in America.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-3ym83w53', 'Box Elder County', 'Golden Spike National Historical Park now marks that historic meeting point.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-ak9rz7a6', 'Box Elder County', 'Box Elder County stretches from the Great Salt Lake to the Idaho border.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-wyugztjr', 'Box Elder County', 'The town of Corinne boomed almost overnight after the transcontinental railroad reached it in 1869.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-orw549nt', 'Box Elder County', 'Corinne was nicknamed the Gentile Capital of Utah during its short lived railroad boom.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-vidh3c43', 'Box Elder County', 'The Bear River Migratory Bird Refuge in Box Elder County shelters more than 200 species of birds.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-vnji1ecy', 'Box Elder County', 'Brigham City has held its Peach Days harvest festival every September since 1904.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-0iie9d42', 'Utah', 'Pioneers first entered the Salt Lake Valley on July 24, 1847.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-cof03nl1', 'Utah', 'Utah became the 45th state of the United States on January 4, 1896.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-p8n1yvwt', 'Utah', 'The Great Salt Lake is the largest natural lake west of the Mississippi River.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-qhf7iedm', 'Utah', 'Utah is nicknamed the Beehive State as a symbol of industry and cooperation.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-o7dcmv0l', 'Utah', 'Five national parks lie entirely within the state of Utah.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-dwbr140f', 'Utah', 'The Bonneville Salt Flats have hosted land speed racing for over a century.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-egmqcpmd', 'Utah', 'Salt Lake City has served as Utah''s capital since before statehood.');
INSERT INTO content_sources (id, topic, text) VALUES ('seed-vq7tl9ow', 'Utah', 'Utah''s landscape ranges from red rock desert to snow capped mountains.');
